export const data=[{"id":1,"course_code":"AGB","course_name":"Augsburg Airport","professor":"Melba Stennet","status":false},
    {"id":2,"course_code":"GNS","course_name":"Binaka Airport","professor":"Yolanthe Swayte","status":true},
    {"id":3,"course_code":"SUN","course_name":"Friedman Memorial Airport","professor":"Madalena Blasl","status":false},
    {"id":4,"course_code":"PVO","course_name":"Reales Tamarindos Airport","professor":"Wilhelmine Jochen","status":true},
    {"id":5,"course_code":"CTK","course_name":"Canton Municipal Airport","professor":"Trude Kneal","status":true},
    {"id":6,"course_code":"OTT","course_name":"Andre Maggi Airport","professor":"Gray Abbey","status":true},
    {"id":7,"course_code":"CMQ","course_name":"Clermont Airport","professor":"Paulie Alden","status":false},
    {"id":8,"course_code":"PON","course_name":"Poptún Airport","professor":"Tabina Strafford","status":true},
    {"id":9,"course_code":"PCP","course_name":"Principe Airport","professor":"Oswald Severy","status":true},
    {"id":10,"course_code":"RJN","course_name":"Rafsanjan Airport","professor":"Gasparo Padbery","status":false},
    {"id":11,"course_code":"HLL","course_name":"Hillside Airport","professor":"Cori Long","status":false},
    {"id":12,"course_code":"CYL","course_name":"Coyoles Airport","professor":"Alix Heiner","status":false},
    {"id":13,"course_code":"PMF","course_name":"Parma Airport","professor":"Devon Chrisp","status":false},
    {"id":14,"course_code":"PPE","course_name":"Mar de Cortés International Airport","professor":"Kennan Huscroft","status":true},
    {"id":15,"course_code":"PKF","course_name":"Park Falls Municipal Airport","professor":"Clarke Rominov","status":false},
    {"id":16,"course_code":"XTO","course_name":"Taroom Airport","professor":"Darnell Lavelle","status":true},
    {"id":17,"course_code":"CBK","course_name":"Shalz Field","professor":"Carmelita Powney","status":false},
    {"id":18,"course_code":"LPO","course_name":"La Porte Municipal Airport","professor":"Hinda Spavon","status":false},
    {"id":19,"course_code":"PZS","course_name":"Maquehue Airport","professor":"Dario Cymper","status":true},
    {"id":20,"course_code":"XGG","course_name":"Gorom-Gorom Airport","professor":"Alic McKitterick","status":true},
    {"id":21,"course_code":"FME","course_name":"Tipton Airport","professor":"Tremaine Yesipov","status":false},
    {"id":22,"course_code":"ZSW","course_name":"Prince Rupert/Seal Cove Seaplane Base","professor":"Rock Bradshaw","status":false},
    {"id":23,"course_code":"PIP","course_name":"Pilot Point Airport","professor":"Chantalle Lavender","status":false},
    {"id":24,"course_code":"PYY","course_name":"Mae Hong Son Airport","professor":"Ondrea Signorelli","status":false},
    {"id":25,"course_code":"GRB","course_name":"Austin Straubel International Airport","professor":"Tova Wharby","status":true},
    {"id":26,"course_code":"ELP","course_name":"El Paso International Airport","professor":"Booth Timberlake","status":false},
    {"id":27,"course_code":"GHK","course_name":"Gush Katif Airport","professor":"Robers Saphin","status":true},
    {"id":28,"course_code":"YGY","course_name":"Deception Airport","professor":"Ludovico Genner","status":false},
    {"id":29,"course_code":"TGC","course_name":"Tanjung Manis Airport","professor":"Tiler Gunton","status":false},
    {"id":30,"course_code":"TER","course_name":"Lajes Airport","professor":"Mariette Shill","status":true},
    {"id":31,"course_code":"OKO","course_name":"Yokota Air Base","professor":"Alair Gorrie","status":false},
    {"id":32,"course_code":"AXA","course_name":"Clayton J Lloyd International Airport","professor":"Gordan Fishburn","status":true},
    {"id":33,"course_code":"CYS","course_name":"Cheyenne Regional Jerry Olson Field","professor":"Vidovik Colloby","status":true},
    {"id":34,"course_code":"SDK","course_name":"Sandakan Airport","professor":"Agretha Sandon","status":false},
    {"id":35,"course_code":"JSU","course_name":"Maniitsoq Airport","professor":"Albina Batalini","status":false},
    {"id":36,"course_code":"REB","course_name":"Rechlin-Lärz Airport","professor":"Bertha Josovitz","status":true},
    {"id":37,"course_code":"ALW","course_name":"Walla Walla Regional Airport","professor":"Bink Tytler","status":true},
    {"id":38,"course_code":"ALJ","course_name":"Alexander Bay Airport","professor":"Melba Gilliatt","status":true},
    {"id":39,"course_code":"WYB","course_name":"Yes Bay Lodge Seaplane Base","professor":"Ianthe Gridley","status":true},
    {"id":40,"course_code":"AIM","course_name":"Ailuk Airport","professor":"Pascale Pick","status":false},
    {"id":41,"course_code":"AMD","course_name":"Sardar Vallabhbhai Patel International Airport","professor":"Arlin Bulluck","status":true},
    {"id":42,"course_code":"TLD","course_name":"Limpopo Valley Airport","professor":"Carson Minget","status":false},
    {"id":43,"course_code":"VAS","course_name":"Sivas Nuri Demirağ Airport","professor":"Danni Millgate","status":false},
    {"id":44,"course_code":"ARS","course_name":"Aragarças Airport","professor":"Minor Worsnip","status":false},
    {"id":45,"course_code":"YPZ","course_name":"Burns Lake Airport","professor":"Michelina Kimbrey","status":true},
    {"id":46,"course_code":"UMY","course_name":"Sumy Airport","professor":"Nari Peyro","status":true},
    {"id":47,"course_code":"BMX","course_name":"Big Mountain Airport","professor":"Francois Mamwell","status":true},
    {"id":48,"course_code":"TUQ","course_name":"Tougan Airport","professor":"Agnesse Bruinemann","status":true},
    {"id":49,"course_code":"ROC","course_name":"Greater Rochester International Airport","professor":"Graeme Babbs","status":false},
    {"id":50,"course_code":"ENJ","course_name":"El Naranjo Airport","professor":"Roxi Harvie","status":true},
    {"id":51,"course_code":"TR7","course_name":"Ottawa / Rockcliffe Seaplane Base","professor":"Son Loseby","status":false},
    {"id":52,"course_code":"LML","course_name":"Lae Island Airport","professor":"Tiffani Verman","status":true},
    {"id":53,"course_code":"YOJ","course_name":"High Level Airport","professor":"Constance Merrigan","status":false},
    {"id":54,"course_code":"PKR","course_name":"Pokhara Airport","professor":"Trudie Corryer","status":true},
    {"id":55,"course_code":"BIE","course_name":"Beatrice Municipal Airport","professor":"Pearl Martinets","status":false},
    {"id":56,"course_code":"CUP","course_name":"General Francisco Bermúdez Airport","professor":"Adi Gillmore","status":false},
    {"id":57,"course_code":"RVR","course_name":"Green River Municipal Airport","professor":"Ashleigh Derges","status":true},
    {"id":58,"course_code":"ZTR","course_name":"Zhytomyr Airport","professor":"Wallie Barthot","status":true},
    {"id":59,"course_code":"CEO","course_name":"Waco Kungo Airport","professor":"Lynnett Hause","status":true},
    {"id":60,"course_code":"KBX","course_name":"Kambuaya Airport","professor":"Lexi Meechan","status":true},
    {"id":61,"course_code":"BZP","course_name":"Bizant Airport","professor":"Elvin Kolis","status":true},
    {"id":62,"course_code":"FEN","course_name":"Fernando de Noronha Airport","professor":"Pauly Espadater","status":false},
    {"id":63,"course_code":"KRO","course_name":"Kurgan Airport","professor":"Stormie Dregan","status":false},
    {"id":64,"course_code":"AEX","course_name":"Alexandria International Airport","professor":"Corrine Dunderdale","status":false},
    {"id":65,"course_code":"RJB","course_name":"Rajbiraj Airport","professor":"Dominga Warbey","status":true},
    {"id":66,"course_code":"ENT","course_name":"Eniwetok Airport","professor":"Bryn Bear","status":true},
    {"id":67,"course_code":"XSB","course_name":"Sir Bani Yas Airport","professor":"Sollie Reilingen","status":false},
    {"id":68,"course_code":"MQD","course_name":"Maquinchao Airport","professor":"Shaylah Backwell","status":false},
    {"id":69,"course_code":"IRN","course_name":"Iriona Airport","professor":"Carmelita Slatford","status":true},
    {"id":70,"course_code":"NKG","course_name":"Nanjing Lukou Airport","professor":"Bryant Cotterill","status":true},
    {"id":71,"course_code":"AUQ","course_name":"Hiva Oa-Atuona Airport","professor":"Sammy Maggiori","status":false},
    {"id":72,"course_code":"YRQ","course_name":"Trois-Rivières Airport","professor":"Trenton Burstow","status":true},
    {"id":73,"course_code":"AKA","course_name":"Ankang Wulipu Airport","professor":"Caryl Baudoux","status":true},
    {"id":74,"course_code":"DOH","course_name":"Hamad International Airport","professor":"Charo Runchman","status":true},
    {"id":75,"course_code":"LGF","course_name":"Laguna Army Airfield","professor":"Ardyth Abramcik","status":false},
    {"id":76,"course_code":"FFT","course_name":"Capital City Airport","professor":"Benyamin Perell","status":false},
    {"id":77,"course_code":"GMP","course_name":"Gimpo International Airport","professor":"Lindy Nodes","status":true},
    {"id":78,"course_code":"GXX","course_name":"Yagoua Airport","professor":"Annie Prestedge","status":true},
    {"id":79,"course_code":"YTG","course_name":"Sullivan Bay Seaplane Base","professor":"Colly Vedyashkin","status":false},
    {"id":80,"course_code":"KUE","course_name":"Kukudu Airport","professor":"Marcela Siemantel","status":false},
    {"id":81,"course_code":"FLW","course_name":"Flores Airport","professor":"Ado Andrey","status":false},
    {"id":82,"course_code":"UMC","course_name":"Umba Airport","professor":"Noella Dowzell","status":true},
    {"id":83,"course_code":"QSX","course_name":"New Amsterdam Airport","professor":"Brenden Backe","status":false},
    {"id":84,"course_code":"NLD","course_name":"Quetzalcóatl International Airport","professor":"Falkner Wilhelmy","status":true},
    {"id":85,"course_code":"CAJ","course_name":"Canaima Airport","professor":"Jeannette Fogg","status":true},
    {"id":86,"course_code":"YWG","course_name":"Winnipeg / James Armstrong Richardson International Airport","professor":"Malory Kase","status":false},
    {"id":87,"course_code":"YHB","course_name":"Hudson Bay Airport","professor":"Simona Reddoch","status":true},
    {"id":88,"course_code":"PIR","course_name":"Pierre Regional Airport","professor":"Garland Stronach","status":true},
    {"id":89,"course_code":"IXH","course_name":"Kailashahar Airport","professor":"Kellen Innott","status":false},
    {"id":90,"course_code":"OPF","course_name":"Opa-locka Executive Airport","professor":"Tybi Wisker","status":false},
    {"id":91,"course_code":"TRU","course_name":"Capitan FAP Carlos Martinez De Pinillos International Airport","professor":"Garner Hulkes","status":false},
    {"id":92,"course_code":"YSE","course_name":"Squamish Airport","professor":"Elianore Vaughan-Hughes","status":false},
    {"id":93,"course_code":"LNG","course_name":"Lese Airport","professor":"Harbert Binns","status":false},
    {"id":94,"course_code":"SSW","course_name":"Stuart Island Airpark","professor":"Maxy Puttnam","status":false},
    {"id":95,"course_code":"XIQ","course_name":"Ilimanaq Heliport","professor":"Allyn Wloch","status":false},
    {"id":96,"course_code":"YDP","course_name":"Nain Airport","professor":"Nelson Zuanelli","status":true},
    {"id":97,"course_code":"DBC","course_name":"Baicheng Chang'an Airport","professor":"Georgie Thebeau","status":true},
    {"id":98,"course_code":"BQU","course_name":"J F Mitchell Airport","professor":"Rowland Rammell","status":true},
    {"id":99,"course_code":"YJP","course_name":"Hinton/Jasper-Hinton Airport","professor":"Tansy Cottill","status":true},
    {"id":100,"course_code":"CKI","course_name":"Croker Island Airport","professor":"Donica Arniz","status":true}]